# The Multi-layer Perceptron



<img align="center" width="500" height="300" src="multi_layer_p.png">

Just as with the perceptron learning algorithm, the multilayer perceptron algorithm is best explained in terms of linear algebriac concepts and partial differentiation. We start with matrix multiplication:


$ x \in \mathbb{R}^d$ and $d \in \mathbb{N}$ be the input space, but this time $ y \in \mathbb{R}^m$ 
note that m may or may not be equal to d
However we not have hidden layers which correspond to several nodes that would be a count dependent on a pervious layer to it and these layers are wieghted or have a specific function that is assigned to them

$ \begin{pmatrix}
w_{11}  & w_{12}  & \cdots  & w_{1n} \\  
 w_{21}& w_{22} &\cdots  & w_{2n}\\ 
 \vdots & \dots & \ddots  & \vdots \\ w_{n1}
 & w_{n2} & \cdots & w_{nn}
\end{pmatrix}  \begin{pmatrix}
x_{1}\\ 
x_{2}\\ 
\vdots\\ 
x_{n}
\end{pmatrix}   $ 

* $\mathcal{X}$: *Input space* consisting of all possible input $x$.
* $\mathcal{Y}$: *Output space* consisting of no or yes credit approval.
* $\mathcal{D}$: *Data set* of tuples in  input-output examples of the form $(x_i, y_i)$, where $f(x_i) = y_i$ and $i \in \mathbb{N}$ .
* $\mathcal{A}$: Learning algorithm which uses $D$ to pick a formula (hypothesis) $g:\mathcal{X}\rightarrow \mathcal{Y}$ so that $g\approx f$, where $g\in \mathcal{H}$. Here $\mathcal{H}$ is the *hypothesis space*. 

Our approximated function g is therefore a composition of functions dependent on the number of layers decided upon

* $ g = (d_{\cdots} \circ k \circ h \circ f)$ : to avoid exhausting the letters of the alphapet 
* $ g = ( f   _{n}\circ  \cdots \circ f_{3} \circ f_{2} \circ f_{1})$

The the loss function is 
* $L(w) = \frac{1}{2}\sigma_{i=1}^{d+1}((\hat{y}- y)^2$
the same update is used with a slight change since due to the compistion of the functions

* $w_{t+1} = w_{t} - \alpha\nabla f_{t}$ 
where 
* $\frac{\partial L}{\partial w}= \frac{\partial L}{\partial \sigma_{i}} \cdots \frac{\partial \sigma_{i+n}}{\partial z} \frac{\partial z}{\partial w} = \nabla f_{t} $

* $\sigma_{i} \in \mathcal{F}^{S}$ : S is a set making $\mathcal{F}^{S}$ a set of function from S to F

Since this is a composite function we are taking the partial derivative we get 
* $\frac{\partial L}{\partial w} = \frac{\partial }{\partial w}( \frac{1}{2}(\hat{y}-y)^2)$

Backpropagation involves finding finding every partial derivative and and using that as a scaling factor for the the new weight variable. 

In [18]:
using CSV

#Using our iris dataset
iris = CSV.read("iris_data.csv")   
println(iris)

150×5 DataFrames.DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species    │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ String⍰    │
├─────┼─────────────┼────────────┼─────────────┼────────────┼────────────┤
│ 1   │ 5.1         │ 3.5        │ 1.4         │ 0.2        │ setosa     │
│ 2   │ 4.9         │ 3.0        │ 1.4         │ 0.2        │ setosa     │
│ 3   │ 4.7         │ 3.2        │ 1.3         │ 0.2        │ setosa     │
│ 4   │ 4.6         │ 3.1        │ 1.5         │ 0.2        │ setosa     │
│ 5   │ 5.0         │ 3.6        │ 1.4         │ 0.2        │ setosa     │
│ 6   │ 5.4         │ 3.9        │ 1.7         │ 0.4        │ setosa     │
│ 7   │ 4.6         │ 3.4        │ 1.4         │ 0.3        │ setosa     │
│ 8   │ 5.0         │ 3.4        │ 1.5         │ 0.2        │ setosa     │
│ 9   │ 4.4         │ 2.9        │ 1.4         │ 0.2        │ setosa     │
│ 10  │ 4.9         │ 3.1        │ 1.5         │ 0.1        │ setosa     

│ 148 │ 6.5         │ 3.0        │ 5.2         │ 2.0        │ virginica  │
│ 149 │ 6.2         │ 3.4        │ 5.4         │ 2.3        │ virginica  │
│ 150 │ 5.9         │ 3.0        │ 5.1         │ 1.8        │ virginica  │


In [19]:


X = zeros(4, 150)
Y = zeros(3, 150)

for i = 1:150
    for j = 1:4
        X[j, i] = iris[i, j]
        if iris[i , 5] == "setosa"
            Y[1, i] = 1.0
        elseif iris[i, 5] == "versicolor"
            Y[2, i] = 1.0
        else
            Y[3, i] = 1.0
        end
    end
end

In [20]:
iris[90,:]

DataFrameRow
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species    │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ String⍰    │
├─────┼─────────────┼────────────┼─────────────┼────────────┼────────────┤
│ 90  │ 5.5         │ 2.5        │ 4.0         │ 1.3        │ versicolor │

In [4]:
X[:,90]     # going to compare with the 90th column

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [5]:
Y[:,90]   # look at the 90 row from Y

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

#### Activation is the sigmoid function σ(s) = 1/(1+exp(-s)) 

In [21]:
# Define sigmoid function and its derivative
σ(s) = 1/(1+exp(-s))
dσ(s) = σ(s)*(1 - σ(s))

# Define softmax function
softmax(a, i) = exp(a[i])/(sum(exp(a[j]) for j = 1:length(a)))

# Define cross-entropy loss function
L(O, y) = -sum(y[i]*log(O[i]) for i = 1:length(y))

# Define Hadamard Product
hadamard(x,y) = [x[i]*y[i] for i = 1:length(x)];

In [22]:
function forward_propagation(x, y, W, b)
    a1 = copy(x)
    z2 = W[1]*a1 + b[1]
    a2 = σ.(z2)
    
    z3 = W[2]*a2 + b[2]
    a3 = σ.(z3)
    
    z4 = W[3]*a3 + b[3]
    a4 = σ.(z4)
    
    a = [a1, a2, a3, a4]
    z = [[0.0], z2, z3, z4]
    O = [softmax(a4, i) for i = 1:length(a4)]
    loss = L(O, y)
    return a, z, O, loss
end

forward_propagation (generic function with 1 method)

In [23]:
forward_propagation(X[:,1], Y[:,1], W, b)

(Array{Float64,1}[[5.1, 3.5, 1.4, 0.2], [0.986708, 0.993298, 0.975211, 0.999824, 0.999188], [0.998409, 0.997497, 0.990155, 0.995949, 0.996755], [2.58249e-7, 2.56373e-7, 2.51972e-7]], Array{Float64,1}[[0.0], [4.30725, 4.99868, 3.67224, 8.64345, 7.11483], [6.44195, 5.98793, 4.61093, 5.50478, 5.72728], [-15.1693, -15.1766, -15.1939]], [0.333333, 0.333333, 0.333333], 1.0986122859501855)

In [24]:
function backpropagation(x, y, W, b)
    a, z, O, loss = forward_propagation(x, y, W, b)
    δ4 = a[4] - y
    δ3 = hadamard(W[3]'*δ4, dσ.(z[3]))
    δ2 = hadamard(W[2]'*δ3, dσ.(z[2]))
    δ = [[0.0], δ2, δ3, δ4]
    return a, δ
end

function ∇L(x, y, W, b)

    a, δ = backpropagation(x, y, W, b)
    
    db1 = copy(δ[2])
    db2 = copy(δ[3])
    db3 = copy(δ[4])
    
    dW1 = δ[2]*a[1]'
    dW2 = δ[3]*a[2]'
    dW3 = δ[4]*a[3]'
    return [db1, db2, db3], [dW1, dW2, dW3]
end


function gradient_descent!(x, y, W, b, α)
    db, dW = ∇L(x, y, W, b)
    for i = 1:length(W)
        W[i] -= α*dW[i]
        b[i] -= α*b[i]
    end
end

gradient_descent! (generic function with 1 method)

In [25]:
function mini_batch_∇L(train_data, train_label, W, b, m)

    i = rand(1:100)
    a, δ = backpropagation(train_data[:,i], train_label[:,i], W, b)
    
    db1 = δ[2]
    db2 = δ[3]
    db3 = δ[4]
    
    dW1 = δ[2]*a[1]'
    dW2 = δ[3]*a[2]'
    dW3 = δ[4]*a[3]'
    
    for _ in 1:m
        j = rand(1:100)
        a, δ = backpropagation(train_data[:,j], train_label[:,j], W, b)
    
        db1 += copy(δ[2])
        db2 += copy(δ[3])
        db3 += copy(δ[4])
    
        dW1 += δ[2]*a[1]'
        dW2 += δ[3]*a[2]'
        dW3 += δ[4]*a[3]'
    end
    
    return [db1/m, db2/m, db3/m], [dW1/m, dW2/m, dW3/m]
end

mini_batch_∇L (generic function with 1 method)

In [26]:
function stochastic_gradient_descent!(train_data, train_label, W, b, α, m)
    db , dW = mini_batch_∇L(train_data, train_label, W, b, m)
    for i = 1:length(W)
        W[i] -= α*dW[i]
        b[i] -= α*b[i]
    end
end

stochastic_gradient_descent! (generic function with 1 method)

In [27]:
# Initialize weight matrices 
W1 = rand(5, 4)
W2 = rand(5, 5)
W3 = rand(3, 5)
W = [W1, W2, W3]

# Initialize bias 
b1 = -1*ones(5)
b2 = -1*ones(5)
b3 = -1*ones(3)
b = [b1, b2, b3]

3-element Array{Array{Float64,1},1}:
 [-1.0, -1.0, -1.0, -1.0, -1.0]
 [-1.0, -1.0, -1.0, -1.0, -1.0]
 [-1.0, -1.0, -1.0]            

In [28]:
function make_prediction(i)
    output = forward_propagation(X[:,i], Y[:,i], W, b)[3]
    println("      setosa       |     versicolor       |     virginica")
    println("----------------------------------------------------------------")
    println(output[1]," | ", output[2], "  |  ", output[3])
end

make_prediction (generic function with 1 method)

In [29]:
for _ in 1:1000000
    j = rand(1:150)
    gradient_descent!(X[:,j], Y[:,j], W, b, 0.37)
end
#verified up to 35:39

In [30]:
make_prediction(12)

      setosa       |     versicolor       |     virginica
----------------------------------------------------------------
0.33396551630470567 | 0.3328213362955562  |  0.333213147399738
